name: fadaa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # تم تحديث حزم فايربيس هنا لحل مشكلة التعارض (Pigeon Error)
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.4
  google_generative_ai: ^0.4.3
  cloud_firestore: ^4.17.4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
