name: fadaa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 1. خدمات فايربيس الأساسية (النواة، المصادقة، قاعدة البيانات)
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.4     # 👈 إضافة جديدة: ضرورية لرفع وحفظ الصور والفيديوهات للقصص والمنشورات
  
  # 2. خدمات جوجل (تسجيل الدخول والذكاء الاصطناعي)
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.4.3
  
  # 3. التعامل مع الوسائط (الصور والفيديوهات)
  image_picker: ^1.1.2          # 👈 إضافة جديدة: لفتح الاستوديو واختيار الصور أو التقاطها بالكاميرا
  video_player: ^2.8.6          # 👈 إضافة جديدة: المحرك الأساسي لتشغيل فيديوهات الريلز (Reels)
  
  # 4. تحسينات واجهة المستخدم (UI & UX)
  cached_network_image: ^3.3.1  # 👈 إضافة جديدة: تحفظ الصور المحملة لتسريع ظهورها وتقليل استهلاك الإنترنت
  timeago: ^3.6.1               # 👈 إضافة جديدة: لتحويل التواريخ المعقدة إلى كلمات بسيطة مثل "منذ ساعتين" أو "منذ يومين"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
